INSERT INTO public.countries (country,country_id) VALUES
	 ('China',1),
	 ('Poland',2),
	 ('Sri Lanka',3),
	 ('Botswana',4),
	 ('Russia',5),
	 ('Dominican Republic',6),
	 ('Mexico',7),
	 ('France',8),
	 ('Japan',9),
	 ('Canada',10);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Tanzania',11),
	 ('Sweden',12),
	 ('Brazil',13),
	 ('Saudi Arabia',14),
	 ('Cyprus',15),
	 ('Colombia',16),
	 ('Mongolia',17),
	 ('Serbia',18),
	 ('Georgia',19),
	 ('Philippines',20);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Ukraine',21),
	 ('Peru',22),
	 ('United States',23),
	 ('Indonesia',24),
	 ('Bulgaria',25),
	 ('Czech Republic',26),
	 ('Pakistan',27),
	 ('Netherlands',28),
	 ('Afghanistan',29),
	 ('Greece',30);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Portugal',31),
	 ('Libya',32),
	 ('Cameroon',33),
	 ('Thailand',34),
	 ('Haiti',35),
	 ('Papua New Guinea',36),
	 ('Azerbaijan',37),
	 ('Venezuela',38),
	 ('Argentina',39),
	 ('Democratic Republic of the Congo',40);
INSERT INTO public.countries (country,country_id) VALUES
	 ('North Korea',41),
	 ('Ireland',42),
	 ('Bosnia and Herzegovina',43),
	 ('Nigeria',44),
	 ('Sudan',45),
	 ('Samoa',46),
	 ('Chile',47),
	 ('Iran',48),
	 ('Ethiopia',49),
	 ('Honduras',50);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Norway',51),
	 ('Slovenia',52),
	 ('Syria',53),
	 ('Finland',54),
	 ('El Salvador',55),
	 ('Cuba',56),
	 ('Bangladesh',57),
	 ('Sierra Leone',58),
	 ('Lebanon',59),
	 ('Jordan',60);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Macedonia',61),
	 ('Germany',62),
	 ('Malaysia',63),
	 ('Bolivia',64),
	 ('Guadeloupe',65),
	 ('Lithuania',66),
	 ('Guatemala',67),
	 ('Morocco',68),
	 ('Mali',69),
	 ('Hungary',70);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Moldova',71),
	 ('Croatia',72),
	 ('Kazakhstan',73),
	 ('South Africa',74),
	 ('Egypt',75),
	 ('Madagascar',76),
	 ('Taiwan',77),
	 ('Somalia',78),
	 ('Ecuador',79),
	 ('Palestinian Territory',80);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Armenia',81),
	 ('Ivory Coast',82),
	 ('Vietnam',83),
	 ('Albania',84),
	 ('Austria',85),
	 ('Zambia',86),
	 ('Republic of the Congo',87),
	 ('Nicaragua',88),
	 ('Belarus',89),
	 ('United Kingdom',90);
INSERT INTO public.countries (country,country_id) VALUES
	 ('South Korea',91),
	 ('Central African Republic',92),
	 ('French Guiana',93),
	 ('Kenya',94),
	 ('Gambia',95),
	 ('Trinidad and Tobago',96),
	 ('Cape Verde',97),
	 ('Uganda',98),
	 ('Barbados',99),
	 ('Myanmar',100);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Italy',101),
	 ('Gabon',102),
	 ('United Arab Emirates',103),
	 ('Tunisia',104),
	 ('Malta',105),
	 ('Iraq',106),
	 ('Spain',107),
	 ('Estonia',108),
	 ('Israel',109),
	 ('Tajikistan',110);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Cambodia',111),
	 ('Australia',112),
	 ('Luxembourg',113),
	 ('Yemen',114),
	 ('Mayotte',115),
	 ('Denmark',116),
	 ('Kyrgyzstan',117),
	 ('Bahrain',118),
	 ('Kosovo',119),
	 ('Zimbabwe',120);
INSERT INTO public.countries (country,country_id) VALUES
	 ('New Zealand',121),
	 ('Montenegro',122),
	 ('Comoros',123),
	 ('Latvia',124),
	 ('Chad',125),
	 ('Saint Kitts and Nevis',126),
	 ('Mauritania',127),
	 ('Mauritius',128),
	 ('Falkland Islands',129),
	 ('Angola',130);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Costa Rica',131),
	 ('Nepal',132),
	 ('Paraguay',133),
	 ('French Polynesia',134),
	 ('Uzbekistan',135),
	 ('Niger',136),
	 ('Malawi',137),
	 ('Panama',138),
	 ('Burkina Faso',139),
	 ('Togo',140);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Eritrea',141),
	 ('Guinea',142),
	 ('Senegal',143),
	 ('Andorra',144),
	 ('American Samoa',145),
	 ('Jamaica',146),
	 ('Micronesia',147),
	 ('Equatorial Guinea',148),
	 ('Martinique',149),
	 ('Swaziland',150);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Laos',151),
	 ('Qatar',152),
	 ('Turkmenistan',153),
	 ('Hong Kong',154),
	 ('Mozambique',155),
	 ('Slovakia',156),
	 ('Namibia',157),
	 ('Bahamas',158),
	 ('Uruguay',159),
	 ('Burundi',160);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Solomon Islands',161),
	 ('San Marino',162),
	 ('Ghana',163),
	 ('Faroe Islands',164),
	 ('Iceland',165),
	 ('Liberia',166),
	 ('Belgium',167),
	 ('Monaco',168),
	 ('Aland Islands',169),
	 ('Guinea-Bissau',170);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Maldives',171),
	 ('Benin',172),
	 ('Antigua and Barbuda',173),
	 ('Lesotho',174),
	 ('Bermuda',175),
	 ('Guam',176),
	 ('South Georgia and the South Sandwich Islands',177),
	 ('Reunion',178),
	 ('Switzerland',179),
	 ('Bhutan',180);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Kuwait',181),
	 ('New Caledonia',182),
	 ('Guyana',183),
	 ('Dominica',184),
	 ('Seychelles',185),
	 ('Palau',186),
	 ('Belize',187),
	 ('Oman',188),
	 ('Curacao',189),
	 ('Djibouti',190);
INSERT INTO public.countries (country,country_id) VALUES
	 ('East Timor',191),
	 ('Rwanda',192),
	 ('Puerto Rico',193),
	 ('Liechtenstein',194),
	 ('Saint Martin',195),
	 ('U.S. Virgin Islands',196),
	 ('Svalbard and Jan Mayen',197),
	 ('Northern Mariana Islands',198),
	 ('Marshall Islands',199),
	 ('Pitcairn',200);
INSERT INTO public.countries (country,country_id) VALUES
	 ('South Sudan',201),
	 ('Turkey',202),
	 ('Isle of Man',203),
	 ('Sao Tome and Principe',204),
	 ('India',205),
	 ('Singapore',206),
	 ('Suriname',207),
	 ('Greenland',208),
	 ('Aruba',209),
	 ('Vanuatu',210);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Niue',211),
	 ('Anguilla',212),
	 ('Fiji',213),
	 ('Bonaire, Saint Eustatius and Saba ',214),
	 ('Brunei',215),
	 ('Tonga',216),
	 ('Nauru',217),
	 ('Kiribati',218),
	 ('Grenada',219),
	 ('Cayman Islands',220);
INSERT INTO public.countries (country,country_id) VALUES
	 ('Saint Vincent and the Grenadines',221),
	 ('Saint Pierre and Miquelon',222),
	 ('Montserrat',223),
	 ('Tuvalu',224),
	 ('Romania',225),
	 ('Tokelau',226),
	 ('French Southern Territories',227),
	 ('Saint Lucia',228),
	 ('Cocos Islands',229),
	 ('Algeria',230);
